services:
  - type: web
    name: lanmed-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lanmed_backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: lanmed-backend.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DEEPL_API_KEY
        sync: false
      - key: DEEPL_API_URL
        value: https://api-free.deepl.com/v2/translate
